# Generated by: Neurodocker version 0.7.0+0.gdc97516.dirty
# Latest release: Neurodocker version 0.7.0
# Timestamp: 2020/06/16 19:58:06 UTC
# 
# Thank you for using Neurodocker. If you discover any issues
# or ways to improve this software, please submit an issue or
# pull request on our GitHub repository:
# 
#     https://github.com/ReproNim/neurodocker

FROM neurodebian:stretch-non-free

USER root

ARG DEBIAN_FRONTEND="noninteractive"

ENV LANG="en_US.UTF-8" \
    LC_ALL="en_US.UTF-8" \
    ND_ENTRYPOINT="/neurodocker/startup.sh"
RUN export ND_ENTRYPOINT="/neurodocker/startup.sh" \
    && apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           apt-utils \
           bzip2 \
           ca-certificates \
           curl \
           locales \
           unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG="en_US.UTF-8" \
    && chmod 777 /opt && chmod a+s /opt \
    && mkdir -p /neurodocker \
    && if [ ! -f "$ND_ENTRYPOINT" ]; then \
         echo '#!/usr/bin/env bash' >> "$ND_ENTRYPOINT" \
    &&   echo 'set -e' >> "$ND_ENTRYPOINT" \
    &&   echo 'export USER="${USER:=`whoami`}"' >> "$ND_ENTRYPOINT" \
    &&   echo 'if [ -n "$1" ]; then "$@"; else /usr/bin/env bash; fi' >> "$ND_ENTRYPOINT"; \
    fi \
    && chmod -R 777 /neurodocker && chmod a+s /neurodocker

ENTRYPOINT ["/neurodocker/startup.sh"]

ENV LANG="C.UTF-8"

ENV LC_ALL="C.UTF-8"

RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           pigz \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/dcm2niix &&             cd /opt/dcm2niix &&             curl -sSLO https://github.com/rordenlab/dcm2niix/releases/download/v1.0.20181125/dcm2niix_25-Nov-2018_lnx.zip &&             unzip dcm2niix_25-Nov-2018_lnx.zip &&             rm dcm2niix_25-Nov-2018_lnx.zip

ENV PATH="/opt/dcm2niix:$PATH"

RUN test "$(getent passwd coder)" || useradd --no-user-group --create-home --shell /bin/bash coder
USER coder

COPY [".", "/home/coder/project"]

USER root

RUN chown -R coder /home/coder/project

USER coder

WORKDIR /home/coder

SHELL [ "/bin/bash", "--login", "-c" ]

ENV CONDA_DIR="/opt/miniconda-latest" \
    PATH="/opt/miniconda-latest/bin:$PATH"
RUN export PATH="/opt/miniconda-latest/bin:$PATH" \
    && echo "Downloading Miniconda installer ..." \
    && conda_installer="/tmp/miniconda.sh" \
    && curl -fsSL --retry 5 -o "$conda_installer" https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && bash "$conda_installer" -b -p /opt/miniconda-latest \
    && rm -f "$conda_installer" \
    && conda update -yq -nbase conda \
    && conda config --system --prepend channels conda-forge \
    && conda config --system --set auto_update_conda false \
    && conda config --system --set show_channel_urls true \
    && sync && conda clean -y --all && sync \
    && conda create -y -q --name neuro \
    && conda install -y -q --name neuro \
           "python=2.7" \
    && sync && conda clean -y --all && sync \
    && sed -i '$isource activate neuro' $ND_ENTRYPOINT

# make conda activate command available from /bin/bash --login shells
RUN echo ". $CONDA_DIR/etc/profile.d/conda.sh" >> ~/.profile

RUN conda init bash

RUN conda activate neuro && pip install -e /home/coder/project/[test]

USER root

ENTRYPOINT ["/neurodocker/startup.sh", "xnat_downloader"]

RUN echo '{ \
    \n  "pkg_manager": "apt", \
    \n  "instructions": [ \
    \n    [ \
    \n      "base", \
    \n      "neurodebian:stretch-non-free" \
    \n    ], \
    \n    [ \
    \n      "env", \
    \n      { \
    \n        "LANG": "C.UTF-8" \
    \n      } \
    \n    ], \
    \n    [ \
    \n      "env", \
    \n      { \
    \n        "LC_ALL": "C.UTF-8" \
    \n      } \
    \n    ], \
    \n    [ \
    \n      "install", \
    \n      [ \
    \n        "pigz" \
    \n      ] \
    \n    ], \
    \n    [ \
    \n      "run", \
    \n      "mkdir -p /opt/dcm2niix &&             cd /opt/dcm2niix &&             curl -sSLO https://github.com/rordenlab/dcm2niix/releases/download/v1.0.20181125/dcm2niix_25-Nov-2018_lnx.zip &&             unzip dcm2niix_25-Nov-2018_lnx.zip &&             rm dcm2niix_25-Nov-2018_lnx.zip" \
    \n    ], \
    \n    [ \
    \n      "env", \
    \n      { \
    \n        "PATH": "/opt/dcm2niix:$PATH" \
    \n      } \
    \n    ], \
    \n    [ \
    \n      "user", \
    \n      "coder" \
    \n    ], \
    \n    [ \
    \n      "copy", \
    \n      [ \
    \n        ".", \
    \n        "/home/coder/project" \
    \n      ] \
    \n    ], \
    \n    [ \
    \n      "user", \
    \n      "root" \
    \n    ], \
    \n    [ \
    \n      "run", \
    \n      "chown -R coder /home/coder/project" \
    \n    ], \
    \n    [ \
    \n      "user", \
    \n      "coder" \
    \n    ], \
    \n    [ \
    \n      "workdir", \
    \n      "/home/coder" \
    \n    ], \
    \n    [ \
    \n      "env", \
    \n      { \
    \n        "SHELL": "/bin/bash" \
    \n      } \
    \n    ], \
    \n    [ \
    \n      "miniconda", \
    \n      { \
    \n        "create_env": "neuro", \
    \n        "conda_install": [ \
    \n          "python=2.7" \
    \n        ] \
    \n      } \
    \n    ], \
    \n    [ \
    \n      "run", \
    \n      "conda init && . /home/coder/.bashrc && . activate neuro && pip install -e /home/coder/project/[test]" \
    \n    ], \
    \n    [ \
    \n      "user", \
    \n      "root" \
    \n    ], \
    \n    [ \
    \n      "entrypoint", \
    \n      "xnat_downloader" \
    \n    ] \
    \n  ] \
    \n}' > /neurodocker/neurodocker_specs.json
